CREATE TABLE Schedule (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    createdate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedate DATETIME NULL
);